# AI SCI 210 - Week 4 Tuesday

## Logistic Regression in scikit-learn

* Import the "mpg" dataset from Seaborn.  (You can see other available datasets using the `get_dataset_names` function.)
* Here we will try to predict whether a car has at least 25 mpg using "weight" and "horsepower".
* Add a Boolean column to the DataFrame indicating whether or not the car has at least 25 mpg.  Call this column "target".

In [17]:
import seaborn as sns

In [18]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [19]:
df = sns.load_dataset("mpg")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [21]:
df = df.dropna(axis=0).copy()

* Add a Boolean column to df indicating True if the car has 25mpg or higher.  Call this column "target".

In [22]:
df["target"] = (df["mpg"] >= 25)

In [23]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,target
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,False
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,False
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,False
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,False
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,False
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,True
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,True
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,True
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,True
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,True

* For some tasks, a 10% success rate is good, sometimes it's not.  What would the success rate of a naive baseline prediction be for this dataset?

In [24]:
df["target"].mean()

np.float64(0.42346938775510207)

In [25]:
1 - df["target"].mean()

np.float64(0.5765306122448979)

In [26]:
(df["target"] == False).mean()

np.float64(0.576530612244898)

Upshot: Can get over 57.5% accuracy just by always predicting False.  In some cases, can get a 98% accuracy doing something similar.  Always should keep this baseline performance in mind when evaluating your Machine Learning model.

* Fit a `LogisticRegression` object using "weight" and "horsepower" for the predictors and using "target" for our target.
* Notice how similar a `LogisticRegression` object from scikit-learn is to a `LinearRegression` object that we saw last week.
* We're going to need to remove some missing values.  Would you expect to use `axis=0` or `axis=1`?

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
clf = LogisticRegression()

In [29]:
df["weight", "horsepower"]

KeyError: ('weight', 'horsepower')

In [ ]:
df[["weight", "horsepower"]]

     weight  horsepower
0      3504       130.0
1      3693       165.0
2      3436       150.0
3      3433       150.0
4      3449       140.0
..      ...         ...
393    2790        86.0
394    2130        52.0
395    2295        84.0
396    2625        79.0
397    2720        82.0

[398 rows x 2 columns]

In [30]:
clf.fit(df[["weight", "horsepower"]], df["target"])

LogisticRegression()

* What accuracy do we have here?

In [32]:
(clf.predict(df[["weight", "horsepower"]]) == df["target"]).mean()

np.float64(0.8596938775510204)

In [33]:
clf2 = LogisticRegression()

In [34]:
clf2.fit(df[["weight", "horsepower"]], df["origin"])

/workspaces/AISCI210-Unit1-ML/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [35]:
clf2.predict(df[["weight", "horsepower"]])

array(['usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'japan', 'japan', 'usa', 'usa', 'usa',
       'japan', 'europe', 'usa', 'usa', 'japan', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'japan', 'japan', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'japan', 'japan', 'japan',
       'japan', 'japan', 'japan', 'japan', 'japan', 'japan', 'japan',
       'europe', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'europe', 'usa', 'japan', 'usa', 'japan', 'japan',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'europe',
       'usa', 'usa', 'usa', 'usa', 'usa', 'japan', 'usa', 'japan',
       'japan', 'japan', 'japan', 'japan', 'usa', 'usa', 'japan', 'japan',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'japan', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'japan', 'japan', 'usa', 'japan', 'japan',
       'japan', 'japan', 'japan', 'usa', 'usa', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa',
       'europe', 'usa', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa',
       'japan', 'usa', 'japan', 'usa', 'japan', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'europe', 'europe',
       'japan', 'japan', 'usa', 'usa', 'usa', 'usa', 'japan', 'japan',
       'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'japan', 'japan', 'japan', 'japan', 'japan', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'japan', 'usa', 'usa', 'usa', 'japan', 'japan',
       'japan', 'japan', 'usa', 'usa', 'usa', 'europe', 'japan', 'europe',
       'japan', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'japan', 'usa', 'japan', 'japan', 'usa', 'usa', 'usa',
       'japan', 'usa', 'usa', 'usa', 'usa', 'japan', 'japan', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'japan', 'japan', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'japan', 'japan', 'japan', 'japan', 'usa',
       'usa', 'usa', 'usa', 'japan', 'japan', 'japan', 'japan', 'usa',
       'usa', 'usa', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'japan',
       'usa', 'japan', 'europe', 'europe', 'usa', 'usa', 'japan', 'japan',
       'japan', 'usa', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'japan', 'japan', 'japan', 'japan', 'japan', 'japan',
       'japan', 'europe', 'japan', 'usa', 'japan', 'japan', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'japan', 'japan',
       'japan', 'europe', 'japan', 'japan', 'japan', 'europe', 'japan',
       'japan', 'japan', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa', 'usa',
       'usa', 'europe', 'japan', 'usa', 'usa'], dtype=object)

In [36]:
clf2.predict(df[["weight", "horsepower"]]) == df["origin"]

0       True
1       True
2       True
3       True
4       True
       ...
393     True
394     True
395    False
396     True
397     True
Name: origin, Length: 392, dtype: bool

In [37]:
(clf2.predict(df[["weight", "horsepower"]]) == df["origin"]).mean()

np.float64(0.7066326530612245)

In [38]:
clf.score(df[["weight", "horsepower"]], df["target"])

0.8596938775510204

In [39]:
clf2.score(df[["weight", "horsepower"]], df["origin"])

0.7066326530612245

* How does that accuracy compare to our naive prediction?

A little better for target.

* What probabilities are found?  Answer using scikit-learn.

In [40]:
clf.predict_proba(df[["weight", "horsepower"]])

array([[9.89393003e-01, 1.06069965e-02],
       [9.99045578e-01, 9.54422059e-04],
       [9.95595607e-01, 4.40439319e-03],
       [9.95558342e-01, 4.44165829e-03],
       [9.92745981e-01, 7.25401937e-03],
       [9.99974027e-01, 2.59731528e-05],
       [9.99992342e-01, 7.65783152e-06],
       [9.99988715e-01, 1.12847150e-05],
       [9.99995212e-01, 4.78842427e-06],
       [9.99840381e-01, 1.59619019e-04],
       [9.98947966e-01, 1.05203422e-03],
       [9.98417629e-01, 1.58237063e-03],
       [9.98234465e-01, 1.76553483e-03],
       [9.99790820e-01, 2.09180165e-04],
       [3.67626540e-01, 6.32373460e-01],
       [6.80925245e-01, 3.19074755e-01],
       [6.68030709e-01, 3.31969291e-01],
       [3.83573410e-01, 6.16426590e-01],
       [1.67699925e-01, 8.32300075e-01],
       [9.05044957e-03, 9.90949550e-01],
       [4.68309397e-01, 5.31690603e-01],
       [3.43430126e-01, 6.56569874e-01],
       [3.69596127e-01, 6.30403873e-01],
       [5.09395473e-01, 4.90604527e-01],
       [4.91729006e-01, 5.08270994e-01],
       [9.99995200e-01, 4.80049869e-06],
       [9.99978871e-01, 2.11288230e-05],
       [9.99987875e-01, 1.21245253e-05],
       [9.99988716e-01, 1.12835720e-05],
       [1.67699925e-01, 8.32300075e-01],
       [2.46695162e-01, 7.53304838e-01],
       [2.79161703e-01, 7.20838297e-01],
       [6.14415643e-01, 3.85584357e-01],
       [9.52844010e-01, 4.71559904e-02],
       [9.18821716e-01, 8.11782845e-02],
       [8.46068169e-01, 1.53931831e-01],
       [9.09766482e-01, 9.02335177e-02],
       [9.99777206e-01, 2.22794164e-04],
       [9.99936656e-01, 6.33442580e-05],
       [9.99503634e-01, 4.96366404e-04],
       [9.99313035e-01, 6.86965365e-04],
       [9.99987886e-01, 1.21135278e-05],
       [9.99962574e-01, 3.74257572e-05],
       [9.99990591e-01, 9.40934004e-06],
       [8.73211962e-01, 1.26788038e-01],
       [1.57176264e-01, 8.42823736e-01],
       [9.08367377e-01, 9.16326231e-02],
       [7.76308427e-01, 2.23691573e-01],
       [1.89105458e-01, 8.10894542e-01],
       [1.80337153e-01, 8.19662847e-01],
       [6.12680027e-02, 9.38731997e-01],
       [8.07971111e-02, 9.19202889e-01],
       [2.08851207e-02, 9.79114879e-01],
       [1.65682325e-02, 9.83431767e-01],
       [1.89879130e-02, 9.81012087e-01],
       [4.45759573e-02, 9.55424043e-01],
       [3.08406823e-01, 6.91593177e-01],
       [1.14650555e-01, 8.85349445e-01],
       [4.38099950e-02, 9.56190005e-01],
       [3.29575535e-01, 6.70424465e-01],
       [1.91714553e-01, 8.08285447e-01],
       [9.99814524e-01, 1.85476180e-04],
       [9.99920844e-01, 7.91559825e-05],
       [9.99384558e-01, 6.15441529e-04],
       [9.99467384e-01, 5.32616079e-04],
       [9.97731745e-01, 2.26825530e-03],
       [9.99993348e-01, 6.65178699e-06],
       [9.99832954e-01, 1.67045918e-04],
       [9.99854699e-01, 1.45300885e-04],
       [9.99968203e-01, 3.17965238e-05],
       [3.65124040e-01, 6.34875960e-01],
       [9.98779257e-01, 1.22074340e-03],
       [9.97997189e-01, 2.00281147e-03],
       [9.99326661e-01, 6.73338821e-04],
       [9.99275238e-01, 7.24762017e-04],
       [8.76050933e-01, 1.23949067e-01],
       [2.36233814e-01, 7.63766186e-01],
       [6.76796156e-01, 3.23203844e-01],
       [7.88034425e-02, 9.21196557e-01],
       [2.76443162e-01, 7.23556838e-01],
       [2.80715264e-01, 7.19284736e-01],
       [4.85825726e-01, 5.14174274e-01],
       [1.25988932e-01, 8.74011068e-01],
       [1.56217679e-01, 8.43782321e-01],
       [9.99823154e-01, 1.76846497e-04],
       [9.97731745e-01, 2.26825530e-03],
       [9.98781159e-01, 1.21884078e-03],
       [9.98390421e-01, 1.60957937e-03],
       [9.98312249e-01, 1.68775124e-03],
       [9.99995366e-01, 4.63440837e-06],
       [9.99756618e-01, 2.43382107e-04],
       [9.99789648e-01, 2.10352466e-04],
       [9.99538371e-01, 4.61628745e-04],
       [9.99996578e-01, 3.42195472e-06],
       [9.99998914e-01, 1.08589688e-06],
       [9.99611573e-01, 3.88426690e-04],
       [8.91769132e-01, 1.08230868e-01],
       [9.07423833e-01, 9.25761670e-02],
       [7.93018110e-01, 2.06981890e-01],
       [7.13289481e-01, 2.86710519e-01],
       [7.22783661e-01, 2.77216339e-01],
       [1.24753778e-02, 9.87524622e-01],
       [9.99945876e-01, 5.41239477e-05],
       [9.99971990e-01, 2.80102452e-05],
       [9.99951485e-01, 4.85149416e-05],
       [9.99956157e-01, 4.38434884e-05],
       [7.11596962e-01, 2.88403038e-01],
       [2.34746457e-01, 7.65253543e-01],
       [1.54578097e-01, 8.45421903e-01],
       [3.59734812e-01, 6.40265188e-01],
       [1.80754504e-01, 8.19245496e-01],
       [2.21697680e-01, 7.78302320e-01],
       [5.95287644e-01, 4.04712356e-01],
       [2.47219766e-01, 7.52780234e-01],
       [9.99064787e-01, 9.35212583e-04],
       [9.99994462e-01, 5.53797423e-06],
       [1.16120418e-02, 9.88387958e-01],
       [9.76978282e-02, 9.02302172e-01],
       [4.58739557e-01, 5.41260443e-01],
       [8.54730345e-01, 1.45269655e-01],
       [9.95113425e-01, 4.88657547e-03],
       [7.46067331e-01, 2.53932669e-01],
       [8.94599635e-01, 1.05400365e-01],
       [9.99537952e-01, 4.62047652e-04],
       [8.20074452e-01, 1.79925548e-01],
       [7.71904195e-01, 2.28095805e-01],
       [9.20282437e-01, 7.97175627e-02],
       [3.76656795e-02, 9.62334320e-01],
       [2.44660142e-01, 7.55339858e-01],
       [2.48460965e-02, 9.75153903e-01],
       [2.42349634e-01, 7.57650366e-01],
       [9.75908172e-01, 2.40918281e-02],
       [9.78535813e-01, 2.14641874e-02],
       [9.70597397e-01, 2.94026028e-02],
       [9.98963625e-01, 1.03637527e-03],
       [9.99874559e-01, 1.25441147e-04],
       [9.99751765e-01, 2.48234579e-04],
       [9.99744742e-01, 2.55257738e-04],
       [9.99563683e-01, 4.36316589e-04],
       [1.65177083e-01, 8.34822917e-01],
       [3.90176940e-02, 9.60982306e-01],
       [1.59634049e-01, 8.40365951e-01],
       [7.41032044e-03, 9.92589680e-01],
       [3.18546403e-02, 9.68145360e-01],
       [8.97933962e-02, 9.10206604e-01],
       [8.59503056e-02, 9.14049694e-01],
       [1.21871040e-01, 8.78128960e-01],
       [4.73856921e-01, 5.26143079e-01],
       [3.55141747e-01, 6.44858253e-01],
       [4.31251161e-02, 9.56874884e-01],
       [8.78022912e-01, 1.21977088e-01],
       [9.55315218e-01, 4.46847819e-02],
       [7.70161299e-01, 2.29838701e-01],
       [6.07375321e-01, 3.92624679e-01],
       [9.99953364e-01, 4.66363816e-05],
       [9.99659136e-01, 3.40863701e-04],
       [9.99778872e-01, 2.21128498e-04],
       [9.99842727e-01, 1.57272721e-04],
       [9.90002990e-01, 9.99701031e-03],
       [9.86586205e-01, 1.34137945e-02],
       [9.83635173e-01, 1.63648266e-02],
       [9.69037717e-01, 3.09622831e-02],
       [8.95376089e-01, 1.04623911e-01],
       [9.34641614e-01, 6.53583861e-02],
       [9.71714801e-01, 2.82851987e-02],
       [1.00978593e-01, 8.99021407e-01],
       [3.92833032e-01, 6.07166968e-01],
       [7.78296480e-01, 2.21703520e-01],
       [3.02114780e-01, 6.97885220e-01],
       [6.08815749e-01, 3.91184251e-01],
       [9.49098104e-02, 9.05090190e-01],
       [5.13322648e-01, 4.86677352e-01],
       [7.84431892e-01, 2.15568108e-01],
       [4.24627659e-02, 9.57537234e-01],
       [8.25647026e-01, 1.74352974e-01],
       [5.90472879e-01, 4.09527121e-01],
       [6.74997480e-01, 3.25002520e-01],
       [7.74782629e-01, 2.25217371e-01],
       [7.98673202e-01, 2.01326798e-01],
       [1.17539583e-02, 9.88246042e-01],
       [3.17013431e-01, 6.82986569e-01],
       [1.51218130e-01, 8.48781870e-01],
       [4.65112308e-01, 5.34887692e-01],
       [1.50070875e-01, 8.49929125e-01],
       [1.58670057e-01, 8.41329943e-01],
       [9.99158713e-01, 8.41286689e-04],
       [9.99472959e-01, 5.27040990e-04],
       [9.94978854e-01, 5.02114576e-03],
       [9.99558957e-01, 4.41043421e-04],
       [8.96194353e-01, 1.03805647e-01],
       [9.40665231e-01, 5.93347686e-02],
       [6.24591277e-01, 3.75408723e-01],
       [7.68462660e-01, 2.31537340e-01],
       [2.16985526e-02, 9.78301447e-01],
       [4.68026672e-02, 9.53197333e-01],
       [4.24627659e-02, 9.57537234e-01],
       [1.17539583e-02, 9.88246042e-01],
       [9.65602802e-01, 3.43971984e-02],
       [8.73568547e-01, 1.26431453e-01],
       [9.79292682e-01, 2.07073183e-02],
       [8.54899192e-01, 1.45100808e-01],
       [3.29955679e-02, 9.67004432e-01],
       [4.89750755e-02, 9.51024924e-01],
       [9.69543491e-02, 9.03045651e-01],
       [2.25044570e-01, 7.74955430e-01],
       [8.83828927e-01, 1.16171073e-01],
       [9.98933683e-01, 1.06631729e-03],
       [8.33941200e-01, 1.66058800e-01],
       [8.49629000e-01, 1.50371000e-01],
       [9.92523560e-01, 7.47643953e-03],
       [9.99938668e-01, 6.13317131e-05],
       [9.98990849e-01, 1.00915077e-03],
       [9.96196531e-01, 3.80346915e-03],
       [9.98204382e-01, 1.79561753e-03],
       [5.12331175e-02, 9.48766883e-01],
       [1.23219736e-01, 8.76780264e-01],
       [1.66612397e-02, 9.83338760e-01],
       [3.33661908e-01, 6.66338092e-01],
       [4.33898778e-02, 9.56610122e-01],
       [9.98347772e-01, 1.65222775e-03],
       [9.93484414e-01, 6.51558637e-03],
       [9.99205826e-01, 7.94173719e-04],
       [9.98850086e-01, 1.14991363e-03],
       [9.70793701e-01, 2.92062988e-02],
       [9.51037436e-01, 4.89625644e-02],
       [9.63580031e-01, 3.64199686e-02],
       [9.46426789e-01, 5.35732108e-02],
       [9.99903687e-01, 9.63134253e-05],
       [9.99807296e-01, 1.92703506e-04],
       [9.99958197e-01, 4.18032991e-05],
       [9.99630462e-01, 3.69537802e-04],
       [6.43754953e-02, 9.35624505e-01],
       [5.29649792e-01, 4.70350208e-01],
       [1.27724164e-01, 8.72275836e-01],
       [5.53519504e-01, 4.46480496e-01],
       [4.02679909e-02, 9.59732009e-01],
       [1.16457542e-01, 8.83542458e-01],
       [4.14123947e-02, 9.58587605e-01],
       [1.22254303e-01, 8.77745697e-01],
       [6.93163102e-01, 3.06836898e-01],
       [7.12691497e-01, 2.87308503e-01],
       [7.76780344e-01, 2.23219656e-01],
       [1.52920146e-02, 9.84707985e-01],
       [2.37161232e-02, 9.76283877e-01],
       [1.88980468e-02, 9.81101953e-01],
       [6.06222364e-02, 9.39377764e-01],
       [1.72813817e-02, 9.82718618e-01],
       [9.55489067e-01, 4.45109327e-02],
       [9.96749529e-01, 3.25047145e-03],
       [9.94548511e-01, 5.45148885e-03],
       [9.63624196e-01, 3.63758042e-02],
       [8.41089943e-01, 1.58910057e-01],
       [6.43800032e-01, 3.56199968e-01],
       [5.15575027e-01, 4.84424973e-01],
       [9.37693435e-01, 6.23065650e-02],
       [8.25240571e-01, 1.74759429e-01],
       [9.44776325e-01, 5.52236752e-02],
       [7.08496162e-01, 2.91503838e-01],
       [9.77813189e-01, 2.21868111e-02],
       [9.76613244e-01, 2.33867560e-02],
       [9.94062211e-01, 5.93778896e-03],
       [9.98080681e-01, 1.91931851e-03],
       [9.84883967e-01, 1.51160332e-02],
       [9.98769267e-01, 1.23073341e-03],
       [6.85948540e-02, 9.31405146e-01],
       [4.96979684e-01, 5.03020316e-01],
       [3.45739538e-01, 6.54260462e-01],
       [1.17122652e-01, 8.82877348e-01],
       [4.65300275e-01, 5.34699725e-01],
       [7.40444165e-01, 2.59555835e-01],
       [5.69937400e-01, 4.30062600e-01],
       [4.15414985e-01, 5.84585015e-01],
       [7.65012075e-01, 2.34987925e-01],
       [9.62294724e-01, 3.77052760e-02],
       [8.49132758e-01, 1.50867242e-01],
       [9.88248574e-01, 1.17514263e-02],
       [5.15449758e-02, 9.48455024e-01],
       [6.50768749e-02, 9.34923125e-01],
       [9.52448601e-01, 4.75513988e-02],
       [6.59803494e-01, 3.40196506e-01],
       [6.32248489e-01, 3.67751511e-01],
       [8.46500655e-01, 1.53499345e-01],
       [9.54885336e-01, 4.51146638e-02],
       [9.95862031e-01, 4.13796889e-03],
       [9.93971138e-01, 6.02886238e-03],
       [9.98051221e-01, 1.94877922e-03],
       [9.96745446e-01, 3.25455373e-03],
       [9.99750675e-01, 2.49324610e-04],
       [9.98810780e-01, 1.18921951e-03],
       [9.89556158e-01, 1.04438415e-02],
       [9.98933683e-01, 1.06631729e-03],
       [4.32833680e-02, 9.56716632e-01],
       [3.63410982e-02, 9.63658902e-01],
       [6.66512170e-02, 9.33348783e-01],
       [3.75306441e-01, 6.24693559e-01],
       [8.52571921e-01, 1.47428079e-01],
       [9.95428867e-01, 4.57113291e-03],
       [6.16025632e-01, 3.83974368e-01],
       [8.95168323e-01, 1.04831677e-01],
       [8.51895902e-02, 9.14810410e-01],
       [7.48213825e-02, 9.25178617e-01],
       [4.10579112e-02, 9.58942089e-01],
       [6.75372153e-02, 9.32462785e-01],
       [5.07242751e-01, 4.92757249e-01],
       [7.61992263e-01, 2.38007737e-01],
       [8.11506490e-01, 1.88493510e-01],
       [4.27364834e-01, 5.72635166e-01],
       [9.89707167e-02, 9.01029283e-01],
       [2.74707011e-02, 9.72529299e-01],
       [6.91699354e-02, 9.30830065e-01],
       [4.09469895e-02, 9.59053010e-01],
       [5.12882227e-01, 4.87117773e-01],
       [6.19035593e-01, 3.80964407e-01],
       [7.24787737e-01, 2.75212263e-01],
       [8.84386380e-01, 1.15613620e-01],
       [1.21650178e-01, 8.78349822e-01],
       [5.36094692e-01, 4.63905308e-01],
       [2.42349634e-01, 7.57650366e-01],
       [3.70735332e-01, 6.29264668e-01],
       [1.27724164e-01, 8.72275836e-01],
       [5.23037872e-02, 9.47696213e-01],
       [7.69134125e-01, 2.30865875e-01],
       [5.23037872e-02, 9.47696213e-01],
       [2.01751273e-02, 9.79824873e-01],
       [4.00137525e-02, 9.59986247e-01],
       [3.96587998e-01, 6.03412002e-01],
       [6.05054519e-01, 3.94945481e-01],
       [2.86731013e-02, 9.71326899e-01],
       [6.35341750e-02, 9.36465825e-01],
       [2.17520774e-02, 9.78247923e-01],
       [9.51091326e-01, 4.89086737e-02],
       [4.65613576e-01, 5.34386424e-01],
       [3.63945528e-01, 6.36054472e-01],
       [1.17921970e-01, 8.82078030e-01],
       [3.09622303e-01, 6.90377697e-01],
       [4.03030529e-01, 5.96969471e-01],
       [4.98906450e-01, 5.01093550e-01],
       [7.79216419e-01, 2.20783581e-01],
       [2.50099584e-01, 7.49900416e-01],
       [1.37166623e-02, 9.86283338e-01],
       [2.62438743e-02, 9.73756126e-01],
       [1.54659214e-02, 9.84534079e-01],
       [5.13581395e-02, 9.48641860e-01],
       [3.63410982e-02, 9.63658902e-01],
       [3.81340595e-02, 9.61865941e-01],
       [4.36036484e-02, 9.56396352e-01],
       [6.24755293e-02, 9.37524471e-01],
       [4.39261901e-02, 9.56073810e-01],
       [1.05711057e-01, 8.94288943e-01],
       [1.00955733e-01, 8.99044267e-01],
       [1.11413569e-01, 8.88586431e-01],
       [1.56902852e-01, 8.43097148e-01],
       [6.01642687e-01, 3.98357313e-01],
       [2.82651913e-01, 7.17348087e-01],
       [7.44633319e-01, 2.55366681e-01],
       [6.58660615e-01, 3.41339385e-01],
       [8.88732592e-01, 1.11267408e-01],
       [9.15125217e-01, 8.48747830e-02],
       [9.61116813e-01, 3.88831873e-02],
       [9.78390387e-01, 2.16096127e-02],
       [7.35251011e-01, 2.64748989e-01],
       [8.81043703e-01, 1.18956297e-01],
       [4.34851382e-01, 5.65148618e-01],
       [4.59252430e-01, 5.40747570e-01],
       [2.98494845e-01, 7.01505155e-01],
       [3.75601712e-01, 6.24398288e-01],
       [3.31113362e-01, 6.68886638e-01],
       [5.52884509e-01, 4.47115491e-01],
       [6.65243297e-01, 3.34756703e-01],
       [5.84673078e-02, 9.41532692e-01],
       [4.85591360e-02, 9.51440864e-01],
       [4.18727537e-02, 9.58127246e-01],
       [4.91560587e-02, 9.50843941e-01],
       [7.00836003e-02, 9.29916400e-01],
       [1.79846248e-01, 8.20153752e-01],
       [1.10024844e-01, 8.89975156e-01],
       [9.56174915e-02, 9.04382508e-01],
       [3.92297869e-02, 9.60770213e-01],
       [3.92297869e-02, 9.60770213e-01],
       [4.25468231e-02, 9.57453177e-01],
       [8.67806975e-01, 1.32193025e-01],
       [6.75450411e-01, 3.24549589e-01],
       [4.74246294e-01, 5.25753706e-01],
       [8.42785887e-01, 1.57214113e-01],
       [5.83695702e-01, 4.16304298e-01],
       [2.42247864e-01, 7.57752136e-01],
       [6.93987484e-01, 3.06012516e-01],
       [5.37948312e-01, 4.62051688e-01],
       [2.81792409e-02, 9.71820759e-01],
       [2.05549602e-01, 7.94450398e-01],
       [3.33964459e-01, 6.66035541e-01],
       [4.35173314e-01, 5.64826686e-01]])

In [41]:
clf2.predict_proba(df[["weight", "horsepower"]])

array([[0.04780721, 0.01722313, 0.93496965],
       [0.01981718, 0.02132623, 0.9588566 ],
       [0.0370198 , 0.0420172 , 0.920963  ],
       ...,
       [0.26386389, 0.39016537, 0.34597074],
       [0.28909721, 0.12675769, 0.5841451 ],
       [0.25952226, 0.09892273, 0.64155502]], shape=(392, 3))

In [42]:
clf2.classes_

array(['europe', 'japan', 'usa'], dtype=object)

In [43]:
df.iloc[2]

mpg                           18.0
cylinders                        8
displacement                 318.0
horsepower                   150.0
weight                        3436
acceleration                  11.0
model_year                      70
origin                         usa
name            plymouth satellite
target                       False
Name: 2, dtype: object

In [44]:
clf.coef_

array([[-0.00282091, -0.05384914]])

In [45]:
clf.intercept_

array([12.34928003])

In [46]:
t = 3436*-0.00282091 + 150*-0.05384914 + 12.34928003

In [47]:
import numpy as np

In [48]:
1/(1+np.exp(-t))

np.float64(0.004404397280338918)

* What probabilities are found?  Answer by computing them directly using the coefficients.

* Draw a scatterplot where you color the points according to our predictions.  Can you recognize the linear decision boundary?

* Draw a scatterplot where you color the points according to whether we predict at least a 95% probability of being 25 mpg (or higher).

* What is the slope of all these decision boundaries?

## Splitting the data into a training set and a test set

* Using scikit-learn's `train_test_split`, fit the classifier on 80% of the data and compare performance on the remaining 20%.
* Why would we typically not be too concerned about overfitting in this particular case?